---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: subsonic-credentials
  namespace: glance
spec:
  encryptedData:
    password: AgBX1AVWik7OCyBFn7icHxXOXT7qqDR/3YQMkUm1vh96TLi2WVqJ5+2+9QdEMIUuCnScRnZcmuKe8qhiJBKzsDKuEO7Wmr1YD/HknJT1CB95R+UF5HPYptVKQu2EHAOzZRGLdereTtlF9kU9HFYP23HHxdrdFtyIBo0G45Lloa4YPbd0pprW8RMm/saiKfRVyW8n0DD/Y3nsmOkqRrJEWbmUfzRl8LnPXJmHLIwkkD+tCskucVNIh9KYA5ydaXbuXrwvxSt6UplGryCqcORoVYIa07WaCP9kgo6WEMa1Mv0XGJOBT28V4f/qbehplnAA92NcmGKLddqJBQIzjtyMBDesGW0/khKHvT+pwM1tpkNL0U9kSa1l7nmLmkZhPqaxtSyI8K047JTnyUd2w4hNutaBfgUIXsCGCxJpd2lCIyYHZqgddJmXr4kINn4kuIL4/bQyUb8Hfza3Kh3G+zB5ID/2UDFNiBYc/pAHOqPIrcTp691/cTNWQYUb6PO8jFPHLgfol4HMsEQzAh5Uvg10NoqIuaoGw1+A9dFoiMPQChou8hPUmdpBcSiSI0dXIDH9gDcOngHFEs96B59JM/AIAmVweSyhC8PYTeknBB7R63IXUT9CWu3mjiKLaq7kEhyg9D84o/5KiTyo7+jRwGnyZPcSXR0buIfMssGxUUQmX4neBNWo+F0nQ6d2NaZM9rGfamPpQQq4UlPLb2avi5OK5d7PP4UMfE7KCsON4jIMasxyE0PufZK6hjPX2TVQUuEooagSbUN6T6Tde6rok9xJ6MEn
    username: AgCCN8oJh6Bq0/0fCk0UkOOeC+545n0BksflhLmr38wU6mOOR6STPJagTFxiBH4uCXogOSxATh+iGy3vto3p1T3cR7IRQPurEicxJTNetEJx+DJnnau59WnjHJoPyGf5FT5HydW4Q0ViZsH02L7cNo1a3+P4hILduZ8vEE5Zy1iD0GlMcNZQH+LTnwaecL3Vbh9f/zS9ZsKgB2NyqCIneElkzUpF/8A9JRabn6fbzKTqnmy+oV9RrdnYI1mBeiVvGWanPuA4mLzsxLjGFcl3BT7AWdJ1L+7oWTYH0XuAENeiZlqLpJjRC5rb5fi2fc3pXO45RIu7Y2xIqDz7hF4EjdwKqK/9nuFs05W8bxxnigNvGU1HyZ0O9frP3F63Kw7Us+A9l/XleGRvAg92W7ZplUSv19kKSXo9y2vo/W6MHBNwAZzXYKxkRWb5Et2PllQYrRpJCpchFy4ORvccd/fvXALcgw1y/BBR1GcNEUATHIXtN6ybgae14i0JNA4bg+WL9fljmTWl3LJ6UV1wSkrwF+76KWZHh4iGUw3857rRD+EF+BMiYbpMOJuLgFIrKk4s5qzw2c1Ddy4rbfFdcb/gRAXG/ClMkCT5jxSOjQ/bA88jBeSWvWNWCi8I8Gf/ek3GsP1rWOl4s5S5DmPcTcK0fPp2UX2zT6/BfRcTmAI4f2403JPI35YbDUVIXzAz4iBN51isyZ23WHz4af/VjY3c5+UimzpHEvg=
  template:
    metadata:
      name: subsonic-credentials
      namespace: glance
    type: Opaque
