---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: subsonic-credentials
  namespace: glance
spec:
  encryptedData:
    password: AgBluHB/1eHmHEqECR+s9FIK7hgntf5NyA4ZuWoA/uO/jSEko/BDzfpPCFDbzdKMhKLxSX/oHm6CpOM47mWb/pxEuXaGjHwxbdbBiUaKhnR80z3yRjA5stRBSCwaRJCfcItoUVUhRK19Kt0xaeDMwHMcpwafTTShbflWwayEbvcd9KEaV0pUOhQ+VUGfUJ3OQQm8t6Y2kHhsdRZy6Ly3wz5fb2RCjnkTXB/snFyagonxt5RI9fEuv+x8WduEnkbwBdGLJU06sHgl5RbW4tWyD4OfHx0B6xiFFYb9BVFvhUNs88y/iGJ/PJl6glXGqEjtn1NlZtbkWiT/4Dyvmm8HNIZkv4aih9jTGJ30hFQ5qW2vMw5cuL28IiozsIVvdRB8WgvBh7j6JCQ7zMIzK38Ry3hgwWMNpjE9pGClXpnMh08LPXkIQpSNkyRbpX8omMibLJ/vJxJzDHJABOAeKgcXURPPNZLcpEYy7MtFkRlyvwVlSdhlbcc5NORK8oEzg+YSRXIjhD0tnMia3k4yBY9NhAjgir2RMfQJiJ4AKKQrGoCGq4AC9ePI3micymrXtjBMthfqc9cUhcqx96k0XpDXS+ecasTqGQcepQSlH1PiSUYlLem3VyVxAwWGwLDgAF1mN3imyVK5QuoH0/IDZVGlJGnU7sJ3OWNT/wfgU9/PQkysSOsVjRk/v3dKH8bFGX4Kk6IYHb0UzVXsmtKFCdaFr3OmqzzM/juX52lRFGZ3q1zUmQouMXDpgFPFON9qNT+dRhiXKCviOuj7xLNaZEHheeER
    username: AgAOQ7Mc67bodnGjvK3lLUTJ3fbitNpQXU84a/eUI3hmSYmPa2TVdt9k5X0bxs5e2yhJurnznCWyg6BMF9nViYEcARrM1RmLyEYRjLqcST1ep7qVW2VUrtPl3ISTtayIEKVboAr0MUf0I59p2WQ8xaFa5S5FbdpoU++JR4bPLlx5g2JaudTaUaOfoJGdDktsE0tCVnreOLQgdEtswR5vVpzV1QbLcHsZOeMyFU1XnKnIoIgrz8qZ2/kn37IAgJ2KiuWKUOzRme2AAC2zl8w39OPrUyBU4niaxFzsVVgkoGILY3JjW6b62SUmAnAdJmmnWflZ/xx3GDYbQaxw0h3112ciA+5VCpvewqA4j0e3wRN2FbExfteMiJHOCUBvSmHH4rQyoLvKqYz49VWDoHnuGToBKDAgzyoeqyzhOwTU+OxZZifxmFhhPYbgRq3o6FCJtHgAlh3rfnB8J314kXW47sKcKau+4kiLYIn9mEoTdnh9LKYWrqRzTgUrL1uZbM6+Q/yp1qdENJXOiIEMcaW1w04HzT9P1mcBFUH3v19/57TI3goKD1n2RocJSMmJ5KtIchLSHLf0CDSIhUrx+2p77oP5AjZA1bkOfL5yInY8k48aJC1KZrKx1kle5OUsUc+PuZihRmE6J4ylflJpFJTgmiHu1UlugphslozeaTaQDwYh2QYzRm4Z18fRxNTMrUY1zDHYGuuseomvkHIHBEr15CxHoyFIkow=
  template:
    metadata:
      name: subsonic-credentials
      namespace: glance
    type: Opaque
