---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sso.dominikstahl.dev`)
      kind: Rule
      services:
        - name: authentik-server
          port: http
