apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2025.8.4"
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    authentik:
      error_reporting:
        enabled: true
      postgresql: ~
    global:
      envFrom:
        - secretRef:
            name: authentik-secrets
      env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__PORT
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: port
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: user
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: password
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: dbname
    redis:
      enabled: false
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    # blueprints:
    #   configMaps:
    #     - forward-auth-blueprints
