apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2025.8.4"
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    authentik:
      error_reporting:
        enabled: true
    global:
      envFrom:
        - secretRef:
            name: authentik-secrets
    redis:
      enabled: false
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    # blueprints:
    #   configMaps:
    #     - forward-auth-blueprints
