---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: arr
  labels:
    app: lidarr
spec:
  selector:
    app: lidarr
  ports:
    - protocol: TCP
      port: 8686
      name: webui
      targetPort: webui
