apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - ingress.yaml
  - pvc.yaml
  - postgres.yaml
  - database.yaml
  - config.yaml
