---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgAhLjl+/mfaDDpQK3wBFo1JpNMKp/CgycCS+5Mth/NBJQU6KLzEmqmUE8zNNKADPjP2qR6juqQaMoEkB9mxzRdGElXBUnLP73K3HbcvOIQ6ChOQwVPfENiBWbJsH18c61inIvrWt6Fh1EVMgi5oaSNUT1Aau4BgkFAf4X00zbDWZpL+NW1YDQJ2qU2O/QLWAQdgLYyqk+UtJ2knVU5TAOO6sjRP5QqSLue9D1R/P7ifCf2iZKhk4Kz7w3IellToUIJN2JkZTvhPkwrTzW3QQeFn4CrIoo7GCaBesgE1h23hE/sJZGb68NGQ9HIh69lWDsaRHuQocteuOLVZNOveyJPUm9Zg3GwqpTR/bRAe2noy3IRShnpbFtoBxVCUf5fJPE7WqlX97ho93Z+PAb3G6Tn/vpLY5vu5l5zhSFi3obLUytb+vxlj6o9yg/rvE9n7cnYsZEIwa8hDjorrP+PTGT++sib057rGApUrB2PCDIwVK3Gm4nq+yIdYh0CMK/4poeo2AwK16hwk50qZ51Cptr2nMZ1IvV3x2boFRcfAugS8VcakK4ROaltPGBrUbEZZ5lReuaRvBEVa8CFNqV7vcrU/KprxbnyMbo8nkTiRQj13gxVPT1LMENT5JXOTLuLX/mvjeJC6MZDO68QimKVrFKFgM7LZmV8JThpnV0buY42zX4wpMqGRzPWfTAQvdldyWByIUl7n3gw=
    username: AgCfYlx3unjG07gc+BWjmAG9A/uOSom2LNqjXLILFtqvdTPrHKLg6w3GfEyVZPYo2AZMkiwwxEhCa9eZMcQtGERSj84JeUcsLI7pLlti3mTHpN5OLkfkFs6UVaClZeAdcVuDd6TfeKcBxxam9OR92bsIVJZaYAxWNdfiTgQOkDbRRHKgPxlZY322nl3ISfOxIq10FcU8gq7N+hiKop51Xi96FKkuZEnHfI5o0bB0glawQgO5w3ZSPjnA4f42ejst2kDJmz8XXeNWwbR3TeOB1RwoCmgpnOF7DP0Gx6hqA0qS6J2xhLBxpThIxkLL2ksOEPCCe7QyspeEtjdWZlREa0VtSrDWaJsJqrGyPX2pYtIh5R2fuCmtNW0qHIB+TZSUJkUuaFuxTIpvEL2mRHninOW1VNCZ/0QyBatMDFymRgDQpS5d/bCngwJuwUX8maGk77Ac/pr1YPyh5W0juQfNDKQ8OgLb3HonTTG0E63Wtqx5UX3nEZLAYim8VN/0glHKj/QxFizQ+kyfMCU6IUA+1CW15wFFbBGw7Y3Kl5xUEisJNtdHsiaJXUhHFTB1d2EPhUWOtnWt2k75AfRYnM0CiKsgoySt0mxHprZVq90TU63ho8t52VklIEFPabwAHXgj0Y5ENrsv22g2Bo/QWGw49RtbDcAD1ryr3V9GJqFvQocjh06gpWIjG4csJ58WhOL23qLvKQelZbc=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: Opaque
