---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgAQ7hmPcQ60jOMbmX/QtWcsVJPgXXSdvh602kAaXGY1HuOX/HsZUzaAofbPZbBpbrZPV0iSD5Kl19Cm57YxaeTV7NxXOcaY08A4rpP0TcsEiN+FmSM3bmFSo/u+HwO6hnKuoP6lcJewJTvwmQseHSkkM+jbznaahdWzmlvXNHN2pVolzMi5Ox31QFOHJYXuRv6DqqzQSKiysPJkCGqr9/cM/HIuKf4Q+pexndxlDmTtts6JPwKMs0b+mxtAEy8DYfvoGXTvDuTep43NTR43KXTb3AinOgU+XjP5XG4bCc0d6Sjc+hMiS9Y4/q+tlW0imfh59B6q/Tz2rPfxVSejTwtaWleSSYKoH/G8yUgPYhRWQvRfNjzQ1GBwVUgxPLcfpv6FX4cIEgRhO5jWZ1Talngdi+jcnpOMDm2NxpOs8ZJCNMM1LBI9lhjBB+diQ1YA/OUU5ssvjOyoxqlehD+Hne7kwDYl34YWiu7zniNQbjTpgAmmk0aKmBbMpMjDuZ50lsfre+D9xQSRsNfuT0vHbceZEj0FxnoXaEBkL6i6Adcb1wGxNTfl13PAt1E4Fcwk3LAckAJJCxWY0oens8gSukICeY2xH6k7NnaslqCfkjpadROT6l5pR7SH9BLr+0OFqYTpa6OZkV2f3sxnfb82Zvi9O1QZU7Qsmv7g7S6XxnO0wPkiSNNEWNa1fdlWvH6hbfliunNq7JQ=
    username: AgBg3ijirCtXipqrs7rFSJfl1t4YYUIlf2wguzzLABUToKVGs2PE+nfj3qlgU0UUiaQ3laPvgFxttEktLdwrzMRQK8R274Y336hvT3XpGZG1sWfVqQHwf5PkehedcER6T0SYY68Lx2CiFiMX8MAJbpYNB6Zn10S0LhoNtk29IdxWOgSuAOJV0Q62HZYQncwD0t1bo3+V/lHwW4IcFMb8B0iXr7hZoNk6cKRnNcVpc3EXYu/itKNZSHMViQONfzfGFWhJIVoW0c1xd2VXnR6BsI9NBLTR8bPF4fxKNb1JSNW444Tm1ZqRugH9HNLzm5Ckcua+fQrUILxElXfzPeBK4m7SSAdx1WlMRy6kHS/vEG7wKiAMSlSgT9zQNUycX9v81z2BlU/FUAaGV81gHQn4cgon/J9GCicL9YtwAs8ACPwT5sQ8qdg87nYHSjSAKq1/MEhwZ1ZYvP40fAV/nV3sSFx3O9dkUpo82UCkK4AgmnSPKD7ePl7uX7EmJhHgEmcWAolobQlRGmN/NhNDRGMABFkV1hk2J+FodLy+jJrCopT33ZPc21I0WLQzg/kERzy/+Z7wPE4/9bVcWrKM9MYTLz08igYmGvVRKwWLcddYsgiReK1Ej7jhy40dHB93UsR/RQcJvTe89Y+M0Kpj69WBpy9ywyb6ON1Wr956XwDrNMHK++fLKmDzYjpJX81Yi65bkRq5h0c5vi4=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: Opaque
