---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgCxoeR8LdxNGjzIYnyGGu0lWnviZ86O9MIC/BIWOP9ghAPDccW309cgyb8VC5Pbsr3gxi4j2IJRcGiY5+5cUo1R9IOllmirKHJRceYqzp6oQhT3QgdUWvWCICF5/84S7y6ahyY1hCxqyFHzqihJQXun4zi8jRZeLtxDOoYR5JiQCZt05ZWktyVsoxUiyHaumpqKiytDb5AfPluVZLvIIKJL/acm4Ff7n7urqcp3aPP+KFYc8Sijsezmj/0c5xe3cnBF2zw9PLmb+w9T+5JjqHfS4NyHGNDbUpwSIMyt4gZJCLb4alcioiU0L6iBHJXrGKGK+Y7mSuJRQmKLuDq8pRJMii8Ed1p1uh7lRN+Y+QZSSyzqpX1EIr5MftbwtfqNTuKzZiV+UNsNOZgzMykg7ooLPmIn/Kw6HTgnRMl1dn47HwSjUbeuaqHv+w0pL8LrnXSIQz6HCruAHuGLIlsL9adMdrlMCsrqMnNo/NAbQGvOngSHB5XMrg7QP1M5+hw6qzEsgy1xJpMy1lnIvd+vR7XjYp5ZGbrVUhax5p4c/joGAwzhwcsW6tt4D2WucC/71q8Qe72+ph7Befcw9qVkt8xAC4kxqsl9zLvg4/iKdnCFmXU6uAla6y9LCnuHKoBqT0GO4Ao7NIRgQDKhCNEAWAZ3DIo7QF8lCL3wGXzMoAqy1N+jsjT1yCaW6GpeDZtfvCQ/dgNknVs=
    username: AgCw+c5owBU7bQ58U7jvjvaRFJ+dt5YVOP4qFsM6scNV+PJ+lToX4QLDoAiVPiZO8BmW2SAwKD3kxQQOih1c6Ae5tXmakJfDKqKCz1wtOmdJEQke0wQ612oFS8AyK/D4fbw7o2jM26GpfAT0Ydyxn/DbGlJrXbej0yvVrTrLZTmWFsb+4iaqKdS1pfJjFHCoR400mE0eFX36Cp5QCDl0hOfLp/Jk0XS69p/orWF8vu+SdyrOFxYVAEGVNXV72IiK30LYrNTggXCnyBbTYZsWGcH8pSWueGKp1ELuQUYfY/2ddkVVyY9OT8ckjd+gDCbISMPmF0CoAPAcRXp9pmlGr4O573u6e0z9LofkknWGbqFQO14AudCCUTHu+NYzb7Z5EpbsueRmmoKugambaKByZ2oxobwi5BWV1ZR5cYlXHKr7NhNjwllkxKS+U6+Z+3If3+Tl5XwJfB9nQMOwBftfapTjDQGUEs54bSsR8K3qqdEbo9jyzrJt/1Dy9VwQmRwXgEVDYugqIcDsbDX6zegwBkV47SsqmdenEnZ2t6oY4j2Je5UqMcsqte7F9ldO8Cj8dnSVrs0Zn8KAH9MxlIJfelYqalt92MwVHpujN8TsCEzOxDVYSSwCA8sUWpF+WoP/CEBy+1pE8rgevAyk0Z6pO+8nRHQIBMAMf8Kv2Yqugg4ReuJQPGaEZR2orP9uU9M0T42fid60fjg=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: Opaque
