---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgC2xH1JWOmEdLlgN+r2NV+tn4u2ltEZ9D6K5rqhOGg17mUWu94SzzXjtT/VXmyThlNro7kOaiHAQJS0oLv8vOkLNBE7ofrcxMOXqQNCEc6k686yy4AyfKcYVI2PumJTzIisdEBf7PpW9bsm2Ppf2kSYUMFA+qA3r5kUNZQGx5LTOg2Wr+jWjoTZLN/rwVzC0vOoSXSyM89bPZEl1vJPVheEQy89MHvAOsaYK5EGUggjASm2gvqqNlmdBwu4DRRHw8BrFCVRNveNZrB7r9PdVCxfypaGINnUry1YVVTiN1yLR6RSkEJt1NXOTuG5C/AEBc7chrNmMUL87YFxsp4nnVxPsfdUKcfLzPDw5Hqo4ERdC/XC2YW6DvdazZAlFlw8DfbRl2lBE8qUQ8hle8Lp+tlaVHjJFS+tAXlGmcw4LtAjJxJVYlMwAP1Hh4WWqrpu8icNiPpve8lfA41HkH5+WrLEIjvB1rw7GNk6/rD/uqKCwmquDGMnFCbC9rWw4igahfrsGJBtJfLcFBnuVTzg28OUxK1qFL5QJ3+c6xGu4t8MzN36mqtclQfNHvay9XGzLpWDy4rlgfOJlRqrc6IV3ToNO261oYaFn9bQkoeZNfvKjMZmyjhKeeQNhNPWGI9w79wBYK45NNOx1wJrGCHnRHSV7PER3AY61BLSxq2opeGerqeX+bbHfUV6nfEfxtcdQwzl+mvAH0E=
    username: AgBAw7CaB0Zsj7Yu8pQwO+MI/QAIT7xqY18PyBy6iN4qYMFKm+ZUSwG3SzPAc4yuGKkeTidb16NSRRyG54XttZ6j1DxNYvIPhbVBW/o3QbiK/97u+opb7rlGSPnWtex2LOagiQYzX+bMzTPilpJWP5xnoi2Ifq4ZLU+m2v2KTCIShKY0D6GoAd4+oS0bgkKtgZqeAW/Tl2quzAnJ1orzyIKxZ2J3I7xgIcY54pE4wyq5Z0YO/t8gs/kAnfcnv3kdigbnpzFZPlJGOwSZ2P3u1WEKeBXkSOUjxqDCe7nmR4oGLHgwYzwZxH8ZD/l7pBqpCgS0owNGOOK5OK1PksHK1PF9oLd9qxA2J6F7EdmDqPywK1F2YX6ct8m3mXT0pIQiRvNUnxW6vJlqJYkHaLPxXiuFMFU2Eoer9Dj31S6ThsgFdJd6uaP5bAJpakURsTWOGbMrXDcq2jE+YOcZY1WAH0rV8OKP6NqTPcO9pa80Ks0NlkRC6OuQzU36AS0zQQuhXzvknFBW2pe6YRhy4q0plJh0OcY4ZtnVClPtP/bO594uppIB2Ui6U0P7fv/DUCI13Z3xsxuRPkmoKtQNNe9CTGPm3z25HYb2wYUxkbFyIFqvq+zEa+bd5pVqUD8vg7CwagQJcvSFDZ/AnBWTXLXtqZWuI6jU5ihRWzLnQJEkJ6FY9A6KEN27CCR4t9YFhtVQQvglVFzFvDc=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: Opaque
