---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgBY3y4Da7kMHze1+nipdEw4SdwGrL5VyHFb1hzG3z00SkZVk3k2AI+lf8MV1Ni8iJhRl6ETOdV0gYUhehp8WSeg9pZMobilmqvt1W7BTEFYwWipxXuRmIhcTy3h5RYK+7WS5/zX6tXmP1w2YBRgl4Z3Uw1Fx76m+b/51TF6PJ3bgjNX82BL4pFsS+Sm6sRRTZY9Lc0TelUcn7riWTjkP/n2oxHs3DyAKP0VbR7sVjarotFaf9BqubHSy0hC1nhN6XJiG3w/kUZJa92SWmy0u3X/aaRWkh9BKMs3nh2dsOZTsA2BiiK6exgQ5qtBiizcefxvo+3/vC4ICUX1U4ilgIF6JIBUjPF4tRPwMhn35dDjCSjGqbWm990fR6oUXT3jGgIcdZeF8Vw5a9JDusX5IM18BGRaLkeiFAxyWUebwxbfkY9aEJh7ZeSARsZ1vUIG4TJs8x4pkCFZqELM4gxI9xdsctYhXcMEe1vYCmCyr/WbhABnn6Cs6TaWXQrg4+d1/IDjOOBGnoixqfGnnHAR9/QVTtiSE85GMTHwHSaBsGi8rTJm2KbZgGFJHdIoIUAgZsRq6ZaesqdtplS48PHW5RR0X03UD14BHLCxC52zt+pGlCYcfZQnQgzlq7baxM7WmFoyz6dde/xfgxsvi8H0hgDHMYNzRmcZjGnsGqxkK3Njc+Lp3Al5Pu4giDN/PWR1IAW10m/tl9Q=
    username: AgBBSVSa7ISlS3VHftSLHFOjh+ecEEOCC4D74t1pGzv/aVKoPKaXQwAb8F05fRiNS+sYa5cxUaBEbSr+P7oCf9QK3lweJ8Nh59It6Rm1f/jDp34UnMkV0YmUhL8iSSEtNRtOp46D8CLPW9z8niBUmEoHbJL37JF5YG1vmDvvpp7J3pIU8rtFsDKw09zBjrHw+zpgmKh5Caqv6/2Hw5aST7W/QTdR4Q7nGPAwXpC1fhGQWk674/qkKnoh5D1yytrqbpzFijVpnnU6F1+qkNe72ky26SlWs65MP/YF/YidGGrs755186Ub3BKWo0UhE9GGgqeSP4H+QpFYtjB7hDkEsBPK0B3e7llSU7FDzteGx/Tx/v9ue2BgtSeqNS88fXf83w594RDJhHeHHOhJKYPGQlPBNRiUjYvAmWVKBqOf2SZLpz+jwso9l2lCHW0fMUzOwbFaT6jkhUhxEkRVcEodMuCihnrXs1ALe4vW+CRkrpi0MUTEAJLLqWWivQiXh6CF3mhNHSjK86RBlyZPwDb2pcEn8m477xR58GprHwMmwZxkUp54ZcA96MLpVo8C97xC27Nd1k0kMepTgoOxwXQ/m4SUMjKCRuPBpzSWYXuzChHv46YImDoBv001HYr6fONItE2dSrTBy5EkKQq3Y3aIUi529egGMIXwoFZEbSJYuAbRxHJcXSJt1zyZfVCacdHx7T7fSUK7DG0=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: Opaque
