---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgCWS5XOxooQC4pEFr7TQPYMrinXMPDu80Y0T+K+kzdrJ4EQC/q61C7euKfbnz1MySo8iJPLg9iBZtn7qVahaCDJyK7m/MFbbbjU3PTRSgyyKW0La58Fo6ThM51elE0+H4b1NC5iM0fWo8iothmHt29Jlzz5xFozgsaCnBcknQ0rQviOCIedk/eU+1ixdoOpI0ctYfEP5NsIG4labBEGuZ2b4di2hoTdRTK/pvnQcCqG+r4hBlop3d9qgPVMVQAM+jZ0dIVs1/cTNYNTN5ivGz87A/4ZO2wjGh0+iX0YDWrGKkL7vpy+r1whxVbyC7dPXsfSBAqk57baW56gu19VzkhsvHdMsI7Io0liM+suf5Ek5ZCGFOxaWCU5UQgdbWyam0Jsd4N7ig5sLYVae+mki0+lGb5o+6nrXsCRsZdKXW+QBvRLD41OrFJvH8cM0GtdxjeflNNJk+R0qmyNzM8Kb5XaSLBmOCwKDtv2XlIBI3HrxEs1BemUOLgtq8zO7XD+qDceE5VGNe+YSHsvcRCSnm+FiVyPsZOGzG71OJuSCI+kXxBDSFJZgYonz1M0YmjwvtJtbt61jsVSWXr+oR9IJufIxXn96u7YVgrdGh8Xs9iShbr7LSr6eQIPzFTKoGPdj+CjZAMLEVd0e3Vksfu/NeDEwIP9mUXBIfLV/47ZmrtkHJaCcn41eitZ3TUrEh/0sKNq12lo5M0=
    username: AgBevdu0KFKGx+ZpX6BlS6QFok7p3A70OYw22/lwIuRjFhjTybUqQ9R8G4csAD9nod1/YY1UBo4mwtk9mQGSf8JQ7bbsBxAS0kWOU1625J56QZYB0UhXeb9LzvKAOoOHZ+Xv9KFrxlUQnDXUMmQNqkrUYMapv45vbuikPAx8brUhIgunZQ7lzFrLkMevEki+LSxpwlbJHoSv+T8XtVi2/mMVFjFXzVOlVL80BjC0hti1d4E0/zI3qRVcxa9CUHY/AFPEyT9kedmgocLl2HKMe2Ic1jMKQMYTb0m04xXV63ASvc3MCE43wCMOgYxlEXWMow+8B1eqeLp+Yyj6XzqTdaSHmQF5KChjwbXhklsUlhzYRajz7c6N56MyiI7MnDh5qrEyhOC8AuyLawD0L1V3MbUndHa6oygbGHUr/ISvhC0dUPiaobCpq+lHJeg42Jr+sXRL4Ypom+aJ4XT6M17akkng9gy2v6GilretkH0+VxQ4m8l03+ks9LCVYygAlyeQstQEt1IO4LRLFriVC/eSwmiL2h9/O5mwQmIEgwKlwXfqHzdR0sSCK+4tOi38biAGYvPyDgY270uB0u9MHGzXk7seSHvsi1M+XwuEfp+YAgCsIS2tyG3hb9JJPvA0Ix8tXWinDUxHXNS8lOLGgsIb33UTH0PLEhtsh7L6WmsGkEy2i7MxmaDJ8ghKxQ7chIkMCMX+jXecRrw=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: Opaque
