---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgA9MxhAw/Q+Lr7+oi577j0qYjifAyimjOl5RpF/4UADVLKzRhoq/g4vnLdAr6C0lDbw6+NFxYA0cmvp8CEHHlpE6QOmvg7mehAs6geKOmxjWK40SFqcrPx4LIuDs9S9p/+YsZRnMSVTdJGf0H+5HQdLeWen3FLf+umGQ4uMdjOe6tgSl2+VW5EwcTR9eJCexKFsEnBbewCIR7WmtdabDeIQ6/CmcrXStnZ+LaIOTBqWtluVmUlyxWqVkBzaWaKopkNKTY8h+ywM3LG6TA5QRlDA0ecJiWe6m/D3kqHP8WDtN7d9zA8PRcp5mFZzXngVJ3Yhz4JvoPfwTtKYBPdxt4Rxe7p2LxI3vRk1WJONl9Gd70XonvPUQfmohAKjfOAl4TRF5mkxV976oz11lgdASeFvG5nddvjulqda3kqYur7Z0+qRUIkFiMvtFLFbvq2p14k80gV1pAovcrURXVGNgb0djVk/pi86k6zXJtEnUOw4Xm3Ytcw5NZ/ZJptYYJbXrV4VRbV2884gnOQZXnT4PHYbXF4ASFNq11sLJus8YBBwKtQLS6GxyN9eiaoX88QXP1YKOwV9UNyZW+dfU0H7DCBEuv25MRNZ26PmU45Y9RRkkR20Rpi4UZaulwbK9H5BBEUMNr/gT1uEHf5pMm7AP7U7ilUx5jEPe2AV2+CT/exqyLO/3AmvSTKHUPRxjYAZQo+GUbdLiCM=
    username: AgBOaHRJM0eJRAtHgAFANUdCcPR0cENY5CenQ54MEDehmvXPJMlDi5n/2r8Qf7LvBd3PT6lGAe97Wtl4Z0rOcwBkPozCdFrCrRnwqXbNL24gF8wq2PNt5kOUOvTGRFbfjvVVar4apXCHu803xladj18sDkBDodURaofDwZ78GWNZUS4sUy38DdAM83qJPGhiJGpAL9WGvNJk4lVT/IA0mjjxCjpSy9d36t0KutVNF8oR1o8FxSOK6XXuAyGZmcZvPr/SXbQFaiDZDJPT/N9NKw13gHt6jtVTxCYD5be8xgUffxL7/oVp5TWKE8sw+YUrcfsPRuJXwo7nNf51R3RBCZEzG6pUdEVwqxbnuj3Pw7ipwziEj0SHm7BUOQvylr44M3Ote3lR7qz0LfYOymgbcVBVU8LwsoD1YNwN+aqhgyiNEl1a1h9EF5/LJVPkEkESLVMqPXHe64Ru/11659C9jWOAHd9aj5ILx+hLGHmVAp9po9cbeSTDYGZCOGwfzvt+BDCwixZ5rxqtvYOZf4Foyo8x7Vmskl7VKipZZxFqHFgYm/cYSkq4SZaAF2d+9YUubSTAne/YTyRAIRrS0qGICvU1R/SAod8ElXdFcAF8SRuR2CFFoGLT6uaCWcg8nCCjrIuE6O8pDwOeDjR8SnzSuZR25dq7ZzjoXQe0mVz1LgH4DG0bP3oXBXfzmojxnHLUDgKTzGuZ3po=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: Opaque
