apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      version: "0.10.1"
      sourceRef:
        kind: HelmRepository
        name: immich
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-pvc
    valkey:
      enabled: true

    controllers:
      main:
        containers:
          main:
            env:
              DB_HOSTNAME: immich-rw.immich.svc.cluster.local
              DB_PORT: "5432"
              DB_USERNAME: immich
              DB_DATABASE_NAME: immich
              DB_PASSWORD: immich
              IMMICH_CONFIG_FILE: /config/immich-config.yaml
    server:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                tag: v2.0.1
      persistence:
        external:
          enabled: true
          existingClaim: immich-ext-pvc
          mountPath: /usr/src/app/externalLibraries
          readOnly: true
        external-manger:
          enabled: true
          existingClaim: immich-ext-manger-pvc
          mountPath: /usr/src/app/externalLibraries_manger
          readOnly: true
        config:
          enabled: true
          type: secret
          name: immich-config
          mountPath: /config
          readOnly: true
      #        external-wolkestahl:
      #          enabled: true
      #          readOnly: true
      #          type: hostPath
      #          hostPath: /Bilder
      #          hostPathType: Directory
      #          mountPath: /usr/src/app/externalLibraries_wolkestahl
    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: v2.0.1
