---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: twonote-secret
  namespace: twonote-timetracking
spec:
  encryptedData:
    GITLAB_TOKEN: AgAJ9Ww8Ly69j9MRYoVNTpayZ06fYz6nCZD5Gg0jm7QNFQWLVhz01ng7hXCgVRTMC7cfw3kC+uvpE0pJnNysqqWIkkVNrCXdAdo48cwq3sD8Equ3+/33umjaUM4EE8uCAjTovy6cyhojSE24MVgEjseLiPynxmtS6Ua/rxinXMAdiyS3kffqKiT8IRg4+opdWzwymkIm1+Xn01YEcAes8PFvH9S8NhYpQP2QPPkgZR8NXkIGKjdyNz26nz0NjnoAGGWOUszeJx6AQ+quMP2/L+QTDjf20jx3LUVYStgxrkjhsDLUwSEeM/CqRRNfMbRFPSJBoDqR1N4X918P4PXSZ/nwrL8fN6FCB4eLh7Frzk48NQdCb3thoAfun4p8E//f9EOvBwmXgd3YKg/COujizYG7Qk0k1alMrTR9J43GJ05XUQrsCycqJo/rJ492AncipjFYtoa/5uDT3RkBeReWSHZsTM+Ly39MqNsD4PgYHl8tJcWPBx1yjO7GA3WlfYV4ov2bqpLXP+CEJ81oPPOS5aQ7c0nMoefNl2bX3MyYdjQIQX49rI/ChUv8nmZy33ud0bGqfpxdusOQ5H+ZwZJ/GYoacMD7C/zoPh37h+ltNeACBkOEZwvphbZPSKDTPjbeIm+YJhe2u/+oQs6+Xgr7BsvQFSG/tFocnsrliDf74k1oeGcvkJcBpnR/u3I9D0tfXcAGEQNsSUO0fbz66RbG/WQkKbV0oeoHMsTRFOt02q9FyLiZ0lhyqw1y7CTfNm9wWs6dAH3UY6xsUbo=
  template:
    metadata:
      name: twonote-secret
      namespace: twonote-timetracking
    type: Opaque
