---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: twonote-secret
  namespace: twonote-timetracking
spec:
  encryptedData:
    GITLAB_TOKEN: AgCFCsherMhRh85S/yFlIhMw9z4iqs4dgsm/5+Of6WbeJFP/pMjFOrroNdBpcXXRoZtdod1qUUoMyaVYuNFSK9GkU1XNIdCl86v87a8VNyv/A6ItaFjfpNBysBjEp+h/E1jUJm8U/Yx9peH93LMfrYwYJqlmnojvlRkmeUG6fcVY3n6r5bsd6/RaMe5F0grBMi6G5nEla/7MhYWTlQwDjO0NQM0hJC0s9wvNQinD6e0rSQTn1VY+P7qwB+LVH2zIfheGnSvmI+5/cKgC6Mwb5w/dAkcdW4n2Bja2MsWlO/O5FDyrKpW8YTe1ybQ/j+GhqhJwB+PRCymCOSLaBlsTeJ9NBhY9KeSiaw3ifsRTuQUOygaRtrrS8hjLNNFmDj5RbY7uDH6nA4NkNoNjI9fFjHbV7uVQSDpbxxDgIxu4+WIOCK0iBx+Ay3LlSZ8i84LibIMdfL3MAQQfqTYNy/sk5wRa2d1gOjFwLzy69sWmnb/stqOxwhCYaLeswj1S5M0Y3aHULywZzR4S/vYvr8AeR78yb3YHWTK9HBkvwF5BDXRebtABVV+Jb1vFWMvmgSuyZe8j5A+Ut/ZfTIZSNXVxf6jGA0QA6JEeF8cPtfg/H4DqEn6YHirBZhtoZjwTTrC6FsNVOTl4Aub4L2rsqy0aIGyjkSmxhIayeqkv+Ft1Uf7Fzuw9Kld9EPaznwACLp0UiBlmchdxe2GmAhXtlZccE7pFMzbQ8RZC9XXi2iAK8bl13a0Vz3iHhP985c8JxKZwNZKSUwpfnNJJDBc=
  template:
    metadata:
      name: twonote-secret
      namespace: twonote-timetracking
    type: Opaque
