---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: arr
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      name: webui
      targetPort: webui
