---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-pvc
  annotations:
    nfs.io/storage-path: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: znc
  labels:
    app: znc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: znc
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
        - name: znc
          image: znc:1.10.1
          ports:
            - name: znc-port
              containerPort: 6697
          volumeMounts:
            - name: znc-data
              mountPath: /znc-data
      volumes:
        - name: znc-data
          persistentVolumeClaim:
            claimName: znc-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: znc-service
spec:
  selector:
    app: znc
  ports:
    - protocol: TCP
      port: 6697
      targetPort: znc-port
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: znc
  namespace: znc
spec:
  entryPoints:
    - znc
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: znc-service
          kind: Service
          port: 6697
