---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-pvc
  annotations:
    nfs.io/storage-path: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: znc
  labels:
    app: znc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: znc
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
        - name: znc
          image: znc:1.10.1
          ports:
            - name: znc-port
              containerPort: 6697
            - name: metrics-port
              containerPort: 8085 # Expose the Prometheus metrics port
          volumeMounts:
            - name: znc-data
              mountPath: /znc-data
      volumes:
        - name: znc-data
          persistentVolumeClaim:
            claimName: znc-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: znc-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/seedpool_metrics"
    prometheus.io/port: "metrics-port"
spec:
  selector:
    app: znc
  ports:
    - name: znc-port
      protocol: TCP
      port: 6697
      targetPort: znc-port
    - name: metrics-port
      protocol: TCP
      port: 8085 # Expose the metrics port on the service
      targetPort: metrics-port
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: znc-ingress
  namespace: znc
  labels:
    app.kubernetes.io/name: znc
  annotations:
    gethomepage.dev/href: "https://znc.dominikstahl.dev"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "ZNC bouncer"
    gethomepage.dev/group: System
    gethomepage.dev/icon: znc
    gethomepage.dev/app: znc
    gethomepage.dev/name: ZNC
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=znc"
    gethomepage.dev/allowGroups: ZNC
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`znc.dominikstahl.dev`)
      kind: Rule
      services:
        - name: znc-service
          kind: Service
          port: 6697
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: znc
  namespace: znc
spec:
  entryPoints:
    - znc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: znc-service
          port: 6697
