---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flux-capacitor
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux.dominikstahl.dev`)
      kind: Rule
      services:
        - name: capacitor
          kind: Service
          port: 9000
