---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hashproxy-pvc
  annotations:
    nfs.io/storage-path: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client