---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngircd-pvc
  annotations:
    nfs.io/storage-path: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngircd
  labels:
    app: ngircd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ngircd
  template:
    metadata:
      labels:
        app: ngircd
    spec:
      containers:
        - name: ngircd
          image: lscr.io/linuxserver/ngircd:latest
          imagePullPolicy: Always
          ports:
            - name: ngircd-port
              containerPort: 6667
          volumeMounts:
            - name: ngircd-data
              mountPath: /config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: ngircd-data
          persistentVolumeClaim:
            claimName: ngircd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ngircd-service
  labels:
    app: ngircd
spec:
  selector:
    app: ngircd
  ports:
    - name: ngircd-port
      protocol: TCP
      port: 6667
      targetPort: ngircd-port
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ngircd
  namespace: ngircd
spec:
  entryPoints:
    - irc
  routes:
    - match: HostSNI(`irc.dominikstahl.dev`)
      services:
        - name: ngircd-service
          port: 6667
  tls: {}
