---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
  namespace: traefik
spec:
  acme:
    email: dominik@samdj.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-certificate
  namespace: traefik
spec:
  dnsNames:
    - "dominikstahl.dev"
    - "*.dominikstahl.dev"
  secretName: cloudflare-certificate
  issuerRef:
    name: cloudflare
