{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token-secret",
    "namespace": "traefik",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token-secret",
        "namespace": "traefik",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-token": "AgCXUp8DfUuvzEumZ7Nryn9PgQmJPhZTXPFB7MooEtygntE/K+HZIBx4VTyMlOYcs1ELEo3mSiUSDgMq/5S0zht8KXXg3zChjzl1UV/6giz71v6wFsUZnCENFAwqZsXsuhkeN7KXXm42nhCPdbJ8BE54rgUCIL+Jvkfb4wIwAp7iq4Taxb6n9ibC7H2LS0vA+U7AzlHf7uFsoYfW6klgW/tKUKYlz+7BZHGc8fHnPEmlq3dlwulGNtEHzhJK7mtsHPBpuPeeAjikF89tz2/sibjzLyGIbqHpXQFY9vmybvlmBZ3eWNkAbwzlLtBC2KvILHXeWVQv4cx3JMRSdhmvt+ubdwa/iadWfZc1ZihvZNvgwjsUt2DvGarrbsvQRt/lfPidnT9h77yxocIIkzE7RnI1AZQmAT3k9gbQSvzIFtsi2EyefRx5EPIXR1at+nfJ6c4AwXWw7tE0Gk1O59Kq0POGyVuQWkrwdsVFrzWR6JQInTMab5mPLPsihIljbJdkMIbeKxhOuk8K/NFtd69A/0PGEIj4CsyubDS2y0vNyv2uIuWQwvAgq/0wi0Qvpn5jwPYRBZwv4XX+c3FNoP0hlw+LljdILqOxp+eHO4mxjhcLkxznolAFO2ADsdN78tQxuA3aV/BdTCps3O4EvQMs2YZXCyuivNmgm/IQ3011i2UvtRSBy9nAyVJA1icscmoSmbu/SFH2mhwZEeIYw3HX+v0n7sSqjyefibuYsUsmgLs2q1dtl+299viu"
    }
  }
}
