---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgB39vs6oRqtJ7pblp+ZRApjPm2gJL4RqBIs1fYp5YfHkoCSG7lpq2r1NIaosuH36vwOuyxM2h707V28i+0izoVEnlSzRD0rPbItDii9Sn8vy1ebIOLcbNL3e7owcE1gG+IBOtr6+ToBYJaDGdrHjnfgbF9mAYK5OZG415bfl+ORrvvye5CSgGlWH+/GfwuhVtvKR02xBKCjgQS/Xd/vPcT/dzIqsDUSyyTW9TuJchT5RPbegxR4VL2W6qLGlND6iYt0tRsNE8EOoaSFUgtUWC8aRMhMABB20xBBxyH+thqWEHXB5mz50jtXtaRncLlbRfyQj1WcO1lGMGUzPVdb9b2xmFy1rUDCTreIot+mX7RUGLlQDmxD1zmDYsT6kvgYImU+oLLSiitemXZYvECViTrmG+ggAOMNpE6qaukG3z/bd72Sgmo1z0wCFR/jwxheTmOCL7A1BJ+r0svM05N4hq8WNA3UxcJrwLa5oO1Dz6SK4wYzddK8CL9xXFaqzChby9zdsdaZK2JcwqRAhH0b3KbhmvxeVTURnsd60nNEzC9L+Hwi1iN+jWbp4RVBo5VuanIObW/cJ/9IdxSL8rgRwrkdLNH5oVeR/853LM9Z8ucyISHYGwYCwUbcn7c4Ec+Vbr1mRWJl5KmmAHnuNgFehqJusMrdo0PMRpxVAX8pZtcVseAwppxdETVHFtrJjf6+pRYmFie4RAZmZzeVxpm7AAYc2PNQ0bmaoE9iOohdH40TfwqihTBy3du+
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: traefik
    type: Opaque
