---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgCMUpOdreHqI5fZpfeytwKWyx+OImiSKslTJ5TxxxNChOShpQarEdlPX8W/GBedEZpisnoQ54QdhTg8UjtESoRP1CdofhZn3o5Ku/u6HCEUgqZCQ7MauPMQ9oRa/1Lhb8r6up4f8TMy9R5ZQ6apUR9f/8LVdUPvbGIMzA6t23j9xrDRnP65k9oxeT2C45zHe5/HGzoU0Q2BXplhI8aUFKP23+dRWSXmyXJ0CDmBSu/NvewFVFh7HiExr+I5PaYJo/RhcgKrCr0ZE7pLYMLABpbc3Sis/7arKMJzUIxpF5IRhx7JNw9WwNGCMEHPHYzCstaFanMrOCd9ST9fnMApcs8UeLbSupLgbxgDfSGTFHErPXFS7xlBIf/cOUan2WaNm+lNEL0PBx6L2BQMeA1E7WsVj5uLw8i/L+t6LGBx8AbmTgEhPXet0fQyrR2IIlSgF47b/bVQpEux+/eWRsrFOteeoT7Ot0zU5RRbgnFERabOZCCKZzxPKcaStc0q0qYRhxLq8cpTfefUW8vKchOuSTl+YmTKJVaXEjEUSgNQw+BTm9Pc1GFwdzAzyP7ITlz6oPEhz2kNF+5Kbr58WebMdeNtLwfbf1FngOL4ZyUS4/c8FZ2E/QqDua7yiNFoCjKK3lPTRlc81X6yAGIIjINZ+5zha06tct6O4JAFRzqjTJF4eXdfmH5HJqE7a4Fd1HHeY3Ju6EODJn7LhT0OeJuP/+ZCbPJa0Y8FgfxUSG+nCRZu5HUIRn25p5Fv
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: traefik
    type: Opaque
