---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgACZYn/M8vD9gzpKTIC0W6bRaaHmfilwQXT+8jFdOYNa7MrmMU7DDlzrROqd0dLNRdNnWIW1CyG3gIQ6qe7GATpuE4sedY3T9E5nHRVX1UQh1qrCRuRRKzvNWjucksqruL9gTevoOMAdsjSw91Raoop6+DPgji6PoT9tL8Z66nAqiK6/imv8wKTnR7upGavjQQm5v7XTe5ozV+HTNahaKdFekq8cEW8pwdfE9ofjxyPX0Auw+CZYucoS3WAq7lrc0TPLRgr0FfYN99+A8Vzqtgu9g3MFBqj0rW59j3+dTUNQ0RF0+jTYcGL4zqrSzUSs1J9xz3X9GaFTkwt4MfiyQ7h2EJYSX3RuICi/IkLxoshmvalLuz0zl9f/3m0NS4xYDhG9pm8zBtgXnCsfiyMa1d1xitWtjaeCkeHfYjE5uJA+rFxmcNIUPo8XBra3KMfXZYE21wVricgI51B4h2wf8scGrfoeR8Pt+cvjLI4h+UPWkWRMcY0QO2nwaeMldl7k51hzaOHl1OjqA7qe36rkoAmcXW2m9zXwxjMxMxQ3Ff+oVPTCuUqy0arHi29/X2VS5nMOG8nP9d15Bs4hPUtzgQGvA0t0/BN2ppPQq00GSI/llm41r9QsFvdMmsXCzzgAuLyah9CtCh2c2Y5SrU9XRIwyILpDS2fXcLZYa5T8+uYrCPsVnfkW0lx3oZzAtKpkGXNlOp3Pgz7KYrZ+MiZZvM95of+cKl5eLqoG9p6ruA+2AVfw9i3U/VP
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: traefik
    type: Opaque
