---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgBHNlLVd+tUvq/kvA+tfn+lbISPXdeSxj5OvmS/RkHdzpyrn5AKRrrXEInNG3iqZ/lK/qg5WCfhEqV0nXOlnK/AqoFiYte3h7SctC0kWERFIxKQtHltGLG8QH/hOAN1dxJzUHuM4kygHsMcvwaDjqHvBTMPjiyCumaLSmqoNMyDax9N+BSl8VWnHFbkZjn3Q3mHqFomFr4D3XE+H3Wy3cLukzpmRRzniKmLcqacuc4gBvUa8ITnqZLqzOrs23UXAjGXB94wtBybZo5uYGNuC1jU7uekRMRPOSac7S96AgldJMQU9srDBzeHmfFZCYqB5OlSuZHci9yC8Foac8BTM1p33H8weF8BtVq3fCBtXBgiS62bTSJjJIFgK/XfhNHXkF8qpz2SI803YbHKAVHY686pueMWyojyMXXTqSmq72Q6KbXI/adPPePJ0bUGt5xO0AmssPmlUaOuPFpzkmlUzejet0P0uv65PtJrlFxVZpIsupsjz8Wqj+u9ou198VYKH6B16peD7rsAq/vK1IOZs/Dt1SEbxi+R2PUAkJ7YghC+JtjSWJlPa5mbMkU26I19NrKpUcjdYcGyvOj8UpDaA7xLfMZfdwcMcNYbVQVURKdbjPBrtKKClE2eRkdGa6CYvw0MYWWYDL8ShCWEAKH9466X3S368V7SsUgCKyV+IKz7Q8kFpipYLUR5+UFCCqek0tc9oaNc/RKKuhsqq5V4DpP554iVwgGGOJ4QMesvvapAgemFvK+p5a0s
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: traefik
    type: Opaque
