---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgAoD63Xc1rZTjaz5Sn4AZXV37eDejmxXbwFw0kLgQ+pA/UmrzUelwwT18NW4oslzunIM6vmyXiNrgYwpdAGpBZTgIMHvtGr9eSpYO2vXolb3j8XNSuBuDOdQpUwRxCa/yGiSXCFbPSA8uCfzv2PYiShjhTSVxkySY1kk0Nnhp8Z2XjC9NCwm1H6KxhJGA3uYUnG7Dyi4u+4UM8jrKaiJ5EV91mWonNYp60MrCF1s6daYOzVBh7vt+o31KYMUrgbex8+4rd4EVFW3bo5eoxqErYBzwcLJx4KTdgB3FulIBbGnv3nKzWLD4WH5zbnmzntAPRyIcQJEQEfd1TdcubqOjoo9Ttv2nP++d6lzYCV4XSSNVty/Y2g1W51VUD9xSIVbV9uT/gOyYe7xUU9QgCzxf2k3Hivq+3o7+Il19P1Ab/1tNuvAalXU7zG0TPO7NXiXhIMgIoJQ4whqr2FWKtEdCbEYqroayub9AOguH5pvUB0llCcpNL3q5P2EaVtRb5wpzxnJ9EOk8x5BLDuwkucVbKDuEBfQuXZFN9IrWXfeZM2jI2Jt4UkZJukgTN45S7iQjo6SJSFwgOGxdGmDkz9lhXV4O6i9hPx6QfLNnhdexuX1fLdUb1GgRzgXzWYybQF7w2ypr3ExEzyMK+mzyJOjKsMrE4Mk9+ImH2E5s8nmL/f4tWnLyqTbwHwiqEWjdjk/Z9LXKZzr9XUCVC787SImh1qJV6mHmo2UPFR9vgbILFMXdG5NU8yiNhT
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: traefik
    type: Opaque
