---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: arr
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.179.172
    path: "/mnt/nvme/media"
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: arr
spec:
  storageClassName: nfs-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
