---
apiVersion: v1
kind: Service
metadata:
  name: fallback-upstream
  namespace: traefik
spec:
  type: ExternalName
  externalName: dominikstahl.dev
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fallback-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/`)
      priority: 1
      kind: Rule
      services:
        - name: fallback-upstream
          port: 443
          scheme: https
          passHostHeader: true
