---
apiVersion: v1
kind: Service
metadata:
  name: fallback-upstream
  namespace: traefik
spec:
  # No selector: we will provide Endpoints pointing to the external IP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fallback-upstream
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.179.160
    ports:
      - name: https
        port: 443
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fallback-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: HostRegexp(`{host:.+}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: fallback-upstream
          port: 443
          # ask Traefik to use TLS to upstream
          scheme: https
          # preserve the original Host header when proxying
          passHostHeader: true
