---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.dominikstahl.dev`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
