apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: "37.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
    ports:
      websecure:
        http3:
          enabled: true
          advertisedPort: 443
        proxyProtocol:
          trustedIPs:
            - "10.0.0.0/8"
            - "192.168.178.0/23"
            - "172.16.0.0/12"
      web:
        proxyProtocol:
          trustedIPs:
            - "10.0.0.0/8"
            - "192.168.178.0/23"
            - "172.16.0.0/12"
      irc:
        port: 6697
        expose:
          default: true
        exposedPort: 6697
        protocol: TCP
        proxyProtocol:
          trustedIPs:
            - "10.0.0.0/8"
            - "192.168.178.0/23"
            - "172.16.0.0/12"
        tls:
          enabled: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: cloudflare-certificate
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowEmptyServices: true
        allowExternalNameServices: true
      kubernetesIngress:
        allowCrossNamespace: true
        allowEmptyServices: true
        allowExternalNameServices: true
    deployment:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: /metrics
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          metricRelabelings:
            - sourceLabels: [__name__]
              separator: ;
              regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
              replacement: $1
              action: drop
          relabelings:
            - sourceLabels: [__meta_kubernetes_pod_node_name]
              separator: ;
              regex: ^(.*)$
              targetLabel: nodename
              replacement: $1
              action: replace
          jobLabel: traefik
          interval: 30s
          honorLabels: true
        prometheusRule:
          enabled: true
          rules:
            - alert: TraefikDown
              expr: up{job="traefik"} == 0
              for: 5m
              labels:
                context: traefik
                severity: warning
              annotations:
                summary: "Traefik Down"
                description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
