apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: "37.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    service:
      type: ClusterIP
      clusterIP: 10.96.0.205
