apiVersion: v1
kind: Pod
metadata:
  name: debugger-pod
  namespace: wireguard
spec:
  nodeName: machinedeploy-workers-7vt6s-gg2vl
  hostNetwork: true
  hostPID: true
  tolerations:
    - operator: "Exists"
  containers:
    - name: debugger
      image: nicolaka/netshoot
      command: ["/bin/sleep", "365d"]
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host
          name: host-root
  volumes:
    - name: host-root
      hostPath:
        path: /
