{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "traefik-wireguard-config",
    "namespace": "wireguard",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "traefik-wireguard-config",
        "namespace": "wireguard",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "wg0.conf": "AgBVvr2Ro69+ro2uec788SfPwofYOo7hrUac4s4l8Ph0kj7vyNaZjnKCTEVL3n6a33bJNLtFXIjaTepl7a8ygkHbc8iKkdlW0v1PLvdcaP0rFQfBn7eLWSZs+tIvwvVIQJM4PcCA/KNO5BS6ak+xAMHEG4XVdvGWxHDSEWfeM5HVIRFlhwwKHsmZASz2doI/Lg/wg51upx2Xc8fJ+BQsZdZYCC54uHF7qg4V0FO0WwRfGqCpwb0kPPEyh1WE71AM8T+TEj4kmW9exZgOc+O2lHNffYgYnhr5GVNNCZTbThD4olzHDNRi8cU1ZNcj826H2w0yIjlO/8hsV56or1Z9tLiI1N2+Gijm2aYGRJnIvMQqhGlnSl3Y363NE+jUWq1U/w1wAYTTdGdK3OTUgUssMm9hXNZP6UqdiUVuu3y3fpuF6UnFT3RofWhJPyPbknNToE0Cv9FU6BOk5xwIajyLTXhtLVh1tImDdWqzXlPcs4QobRgj0DB5KSzzCFVWGBODYQF0vrQ7Sfk4PSgZNBAcHgDhbwTElpBK/ZToACeoAekIJAL84DtGFSkDKHYfYczgGRgAmbh4yh0HbWmPv+ro9gKkkOuH6q9EQGSnBMjMXwGZj5BuPlLtKSP2vLgG+lUtyG2lrPUqRmTslj07UjAb2dBS8+/W2VIwlHvtPZYMEAYwpTsmjz4qnVxyCtYrl5+l4awI698lQ2iXNL9DGM7Gv3sCBDU6qPBEV9IetXH6f0Pk3SbBmSfbRv6mJJxDKlahvfMvcvZYUqcNkX55djoMrujTj2lb5p1TV3DKcO8CT0dV7G25JdIUq4CVwqWIKZGfMzCecvvHeeqHOKGrfK2H2Erl2mXi+GueLIB0is1OMcSH2oTTIxS8Bc6j35njHRG+P6TL0WpaIxAfDPsiNz+rlGDSO7sqLfbjL7ZVcOi41woA83VnbaxlueRuLXC4JhJQJHfs8NkArHTJajU1PCxhMPI6MmqIcxtDGLUIEJ02wfktgAMmpSluebvY03r9VXFgXPUqNedJT8rK5RrOlip2bg8WAkVDJJMk2gWX3Q=="
    }
  }
}
