---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-wireguard-config
  namespace: wireguard
spec:
  encryptedData:
    wg0.conf: AgB0NR5OOQ2H0fv1OU/SsHeCLa2+z+RHnWzCdf3wVb6np2SFfpgHJmPYGHPHTeBQvLwTRjh72X+zsMIwalYwDupG57Rwm7BbBMrCpxdwAjKrLw67Px9FzUE0t/YNw0Td6U9h+ItGZ3X2XjAF0Uox5K5kakbOT0ISXNblQUdvbAmltp2EW7qoaoxRl105S25gwGBcpXsn8srho2GLlv/U09MFIjkm/n+pSYgGrlU4mySXhPK/XD9BU8jxjlFDgffuDnTQPhREWyUKnHgwyKFkqdne7dzB1/t4SVVL0sml3Qi3IQIpMJf4NtANrOL/9xXrwUwq2cVn2uMUZ2fPE+IZ/AqpsxeHeAOkT/vFQxYO69WydEYVx09G/I3kXZ8yVUjZfzjVeZRdBtg0Y0DoQMyG3rzKx4+IipNBUsIU2nlcfJ4VoLnPpj7qk7MOHRlm4wCS016EnUoYTx6wTjZ/ATsdU6cM4VuDduerqHNrf6rG5aNiURuGMgV5xLXjcgGXMscbGqPSdpSL/TH52YNbQIUeGLAKVxQ/3BpcU0uGEApczqA+LsC67CnbhMCDeN0YoV6XCKLrfWOPYObil6j+9bAwKcZdBtNjXGwkWc7Lcpw5iH+KvTuKZWj/pxb6I9Xv3AKNNECb+WDlZCbe7TN8CwqGeu+w5KH8ySF6goMXdynVxMTps31jjujiE49KN1bZMInUR2eBoyKZBN/9Fe3hXiwS/8NhUJsJbC9x4CRHOwGRApX/rExEKArRXA9TirqluHkFrtWsvF9/PIlGlKMgGPv73fgY7cpbIyPpjiZW2hQStWQmQOj10h1XTjUX/w4MWDqT2mYzLgVU2q+5T3QVw8ZHpJ2acWXTlzfr2I958DYjf2C53MH7AHB8q6izgaahTXGcQp0AfBg7I7+5n8asgtgA2S+785QhVN0KZ5vvlCndL63a47zWjM4+0vz75M5EXFO6EmYIKm6kiky1YCrfWh1sloT29sUl8MJyi68nWWMIFJcnLH/Le8n8apIajsTewetwp51u3o3iJYDXL9gHRbWVbq+8rlLNeJ/ne02hnG2aC/DP1ihKAofcZXuu0Nfu43p+Jq3oN5P6t0Wxras9EHBrCcVMmxr2Z7nIq6haGOxIqK0Gj9QVjd9X69HdA/vK9Eh/BErri38H4i6J6HVoGiaLzzfoS576kYwQCdtgu2S3VJp83n9D97EHQhr0LeOigwCGefMhpCN6I2SRSHfi0mKBUFhLRimX/1fBcdzYCYT5T+bNM0TVy+WfV9vnvxMQvA==
  template:
    metadata:
      name: traefik-wireguard-config
      namespace: wireguard
