{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "traefik-wireguard-config",
    "namespace": "wireguard",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "traefik-wireguard-config",
        "namespace": "wireguard",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "wg0.conf": "AgCHSKXOJjEOsIjM5YlJK8pgLSxYQbIawOx0Ynfcpstyv/um81DZHnDEOZLBsxanBmHIDbwgblgTyzKOUI+/AlfYOvkrcxVD7ZYToo4za5RRyLn8NLXayskdvB1VRmRtbFVcOjutenbADH4FMiqYtvxxC7V2GqQz94MrRuPNmNqGxfErI72oB0OonMy+EHfP6QYd/8yUhk2Jg6qXCfnctDaAlAGS4Owzf0mfduWgAirXLemVM/bzn/aOJ7FMQ2bii0Nf2r1Svpj4an1mzUnLbwuGQ86kr4xJbl8xpt+Dq4ay6Tz1vB3WlmFFd0GNBPdRNEaiwUZAODPegRdENvh+fx4m1DLKs1XP/mm2OPtZym1KyIZri3zKvDIgGYMdke/GVvMc2MCQwlzEvL8SpAjv7IbZyhUPqPkIRV3w7JFk0kWkd3hoXeDBV+/S4IFHXFplDVi66IhwbrPNm4yMOgjS8uGMl9oo/ig2SDsaNSSNjTV3P10ANeBCPePG4Z//gV+/gh5ZetU5HZIsK3CtQbiXyUXfZN1b+J0dxGiRMW59gZTGh83q3sux9Z36P8OlVj68IFJdAC4F3UJLRZG3zOOIGWWuyFFdbQUbeMZ3ivz0yQLbMQbXUb7NqvJjq7NILuaF0IX5kYd1uIJmhWshNgKDR12Q4UzrC+AmrgOCZG8Ttb+zMY9Y7cCsGYMsoyDeWYWeokm8vRT9Ci5ICNp7yAek8gLigaGPeJvVFhRUBTUmhmAMEEFZjyxH8cwqB3A+2cEqinRKA8sNsp2X1rMguGNCwyR8oLGPPtWtlb89JapIjd2SFfXNqdKT3fLTcwiyadczS5zZUvGejXeayjtkDehLHOTZxENlwzZw/iDwwMTVZHcbOwNw/KnYYE8ASOPwyBB2tNq7TSVTXn872N6zhN/bnjjQZTxckhoBc/1WHeX9lMn9Fabbld/jm2OtdgY+KgPN7N99fmS+cUarkSMb1k+6shGup0p8wxzYQLjh43KKp35/GJ8r8YqHfyJrK2Wmd/Q8PPO3Hj+eiBpeUZku2XVmT222wHH8IMMpa4hJYd2bdyIDGWvRlFGA0T+GI+Ykf8/lTw1AdvMdFHf3gsOM8YIotT/HGd6BzWfCfGuqtiuGGJJGI1WlYA5uITlnw+mJ9QA+ox0Drd8OO0h+vO/kDQ38TAoqAU2RyyzP8l4t3oFc04IL81NftrUagFfssFQFT1+52VhDFDekC4A08LSPpzjpKwfSvn+BxUJI2MOvhVWgmn+AwaQeUUHrpy3T+DK8SA=="
    }
  }
}
