---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-wireguard-config
  namespace: wireguard
spec:
  encryptedData:
    wg0.conf: AgCfW1DeE8WQi4CLSvZmYCeahm++BKPdz3hEP3FPPJOf3BLf3kSHyzwzpHMKTNlCIJs3YgB+d7BKEg5AAkiV250zQB9R4igZGiy8HgxvPAqLaoU8O94DbfG6qDJJ0BAHWYbB6pOqw/BUmA+CTwnthK7taxIIrtFBAZJphh52cXbOdeC6HpYQO1RdiEk5IOsRXW81ouamcXsiM1JHwGpU4uP9lEdbvbZ26Ar6A32wqMH7u5cRN4FtlfcQodNqrWIqmQqV5Dk1SBCbLAX22ODRm3NgzRh8VL5+oro/bQlF/WWcaNObABzaG+ka64cdugY2x1Qtha46IcgFAUKuDt3hWzvUhQKz2+2uK80GYRkEoCL5mq3ItNgh2Swow0CBgxT2tICQAplkLhIrPI/rjUrRbKVlF1QHR/nmi0h+bnIT+r/xOcWWQr4EPO5iwCGLxBGKPETBkwNIFB01ApJQaBSLuTu/GfZA28iREpQ7VdEe7W8tZnjEQDIh1iSwtiGAlpQGmi3RZj63LJtjb57oBJc4dhrtol25Qy4VRASwgii4H7MT+4ozhZ0MIiLAahcOoArGSW68BZ+lDGWI8Se9Cx6cGXFAnZHP6SVhsFMOXvlPWHhnoGsxOSEeygURSLmtwlbNzt12h+psHqm18xC5pZKKF4KwEkDfIb4YPShZWliNFcqJDXFmpIFw7Z41CYX1eW6M2jk008XbO9Hjo8rxAAbFv3NPWb3pl89/mZJBD+jOVNL35VTvjQJZrvxbm2dIOGYLUK21dzlGoep3ZqmprWiPuIK6ib2VWcwTCMGywXh4QDZxNFVZ6hmaygJV2sMSTuJIV3ZIVTztoZEWd8x7If5cECVmsklPwOUA8qmCd/wOyj8PBMp2hp05Ex+F+EGdu1srdYWFk83SjIDnJkOU0OhjG0pnwdz1cb5u3WXd9VmhgHMNx0o6vja865uiK6ljeviI+ai4yAFVS4VXWlHgdqmrbKvoQgf1/LScvU4VfJJpcx3kEQTvoI7HyZ11Gf8nsqstytVcJWzRdi6RVRTpUiTl+zhVQnKiZqdX7sZAn0WhBbXpZDWn1jfsYt8wgdOD2mXCtYKvRqYrSGrW3gL6GurvVqAbDE2Q9nS77MhSHpRShAmAxyvXkOnH6E5brwKsn8EbCFxntK4j74mqSl+0EtB/GZimV/Tq1j4lzgliYS1n7/RT3iKmeB4NkndxOOabIEQ1AcRKWNgi0W5kOHjcFBBp01yQ4B/X5V5uYJocaTybIX1bMYFv3NCDPPUtvu7BDg==
  template:
    metadata:
      name: traefik-wireguard-config
      namespace: wireguard
