---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-wireguard-config
  namespace: wireguard
spec:
  encryptedData:
    wg0.conf: AgB7e3JubhLxZRBuOh63kZ+ZmU8E4xCT9R1dSF8aA4iUCTuaOkhz2gxitdm8IOvY/LN2JvibPpD6d4ttS3976XLeAkTWTVhAaAfsGMg1qzDQK+mT10AekiIRhqtqQV0ypRaAGl7nXpAmYVqOgAk7Gu1Rq5y5cCS/VKpFJ1YnxCiEGb3fQqReLXSkZKvDM+1RMDOt9G+HSsYrEPXIs4ii6Bvp8VsrWEfWa9o1khdeN+FhnkRAyncvYhiWbfucm6bViJTAppKuk4LBSDongLCqq0zeNDSwTyKpsyyRMYzxrUYmByR4qTHisds2iOfQu534zXNmZfRDdCEs0T6tCiG+EZv/aW86q7GxL5dJx1h8kMStOiI2izCfDSTndTkf72M7DXi2zPsfMHyUE40DuQKllluB149crlT+cogUo89XLy/U4ksW97kIj3NtHagSaEboWbf75vOHkVua85Yb3G3Zi2NM+stHyKslmAlF/trQM7phfrQsF4sNNlDE6Us2nUWme5gWkQy5Npsyjk/Uuh1VMkAwpsyel+vuoJNrDXMWXSnDdxvt67CebpomrNxJkN59WzQey2TWPYtaSAW0mnDy8F2SW2v+fqP8tHk4RA0orw9thTTfLUgyw9dTvBth0D0ST7LNL/Io8tWKRmRTbpsIA9ah/C5mI4lEU/Xv3aezt7W2aOXoIYcigS4P/ZGHe+O2RYEUUZ1FXEOCzwf8FJKoD5VjPxWGqmTGk+ZKlDoXIK+71fGT3LipVItT/LXlUr50uLfqBz2Q5ZK2WQIW4l4efgZY0Leazt+Hoyyy9UYPk2fvmANvbj5KQDeNElGZD0o/Jj68x3wXbrCuv44rqnlLKuAYJXsADMqZIKWQFBIN8ojOou7ESHqbc/7m+t7Bmzsem+PIgjqLA7QXC3xyst0v2a64rdJz9o0uwP2PZkCi7SOryB9zOLzZyEZJYwn4c2p9W/frBWKxhAD9v3NTBK1+bxp5BrWwRWYOa6i5vB/TWcvETzGk7a6XxRgHtn7TWV+k87evRthZ+w0+rhksXzFEOy0OLSQ47p896Acm40u7Uvz8MeWqLI+JvarSemLgQJ/P1ReHkHnCzMRmjU+DAwkOGI7QqYJX9pp+2hhP0wOPzeRCWPI8KucUkqHoM5kGujE6f2/nkzNtNMW6xxvzbewZxqRfucrB39b3yFpWKEv9qFA6ORp0HLuo3teY1vpk0L9RcIFnpEqz4zI+uz5t288zo0erOnHtJhdEGzbH9h+US476BWxn9n2W20ZKiHHXcw==
  template:
    metadata:
      name: traefik-wireguard-config
      namespace: wireguard
