---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingress
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.dominikstahl.dev`)
      kind: Rule
      services:
        - name: n8n
          kind: Service
          port: 80
