apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  releaseName: n8n
  chartRef:
    kind: OCIRepository
    name: n8n
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    resources:
      limits:
        memory: 2048Mi
      requests:
        memory: 512Mi
    main:
      persistence:
        enabled: true
        storageClass: "nfs-client"
        annotations:
          nfs.io/storage-path: data
        type: dynamic
      config:
        n8n:
          enforce.settings.file.permissions: true
          runner.enable: true
          block.env.access.in.node: true
        db:
          sqlite.pool.size: 5
    worker:
      enabled: false
      persistence:
        enabled: false
