---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 12h
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    semver: "1.0.15"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
