---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng-ingress
  namespace: searxng
  labels:
    app.kubernetes.io/name: searxng
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`search.dominikstahl.dev`)
      kind: Rule
      services:
        - name: searxng
          kind: Service
          port: main
