apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  releaseName: searxng
  chartRef:
    kind: OCIRepository
    name: searxng
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    persistence:
      config:
        annotations:
          nfs.io/storage-path: config
