apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  releaseName: searxng
  chart:
    spec:
      chart: searxng
      version: "1.0.1"
      sourceRef:
        kind: HelmRepository
        name: searxng
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    env:
      INSTANCE_NAME: searxng
      BASE_URL: https://searxng.dominikstahl.dev
      BIND_ADDRESS: "0.0.0.0:8080"
    searxng:
      config:
        search:
          formats:
            - html
            - json
          autocomplete: "duckduckgo"
        preferences:
          lock:
            # - categories
            # - language
            - autocomplete
            - favicon
            # - safesearch
            # - method
            - doi_resolver
            # - locale
            # - theme
            # - results_on_new_tab
            # - infinite_scroll
            # - search_on_category_select
            - image_proxy
            - query_in_title
        hostnames:
          replace:
            '(.*\.)?youtube\.com$': "invidious.dominikstahl.dev"
            '(.*\.)?youtu\.be$': "invidious.dominikstahl.dev"
          #     '(.*\.)?reddit\.com$': 'teddit.example.com'
          #     '(.*\.)?redd\.it$': 'teddit.example.com'
          #     '(www\.)?twitter\.com$': 'nitter.example.com'
          #   remove:
          #     - '(.*\.)?facebook.com$'
          low_priority:
            - '(.*\.)?google(\..*)?$'
          high_priority:
            - '(.*\.)?wikipedia.org$'
        ui:
          theme_args:
            simple_style: dark
        server:
          limiter: false
          image_proxy: true
          bind_address: "0.0.0.0:8080"
        redis:
          url: redis://@homelab-searxng-redis:6379/0
        enabled_plugins:
          - "Basic Calculator"
          - "Hash plugin"
          - "Self Information"
          - "Tracker URL remover"
          - "Unit converter plugin"
          - "Hostnames plugin"
          - "Open Access DOI rewrite"
          # - 'Tor check plugin'
    persistence:
      limiter:
        enabled: true
        type: configMap
        name: configmap-searxng-limiter
        mountPath: /etc/searxng/limiter.toml
        subPath: limiter.toml
    redis:
      enabled: true
