apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arr
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
          - name: net.ipv6.conf.all.disable_ipv6
            value: "1"
      containers:
        - name: qbittorrent
          image: ghcr.io/hotio/qbittorrent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8080
              protocol: TCP
              name: webui
            - containerPort: 8080
              protocol: UDP
              name: webui-udp
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
            - name: WEBUI_PORTS
              value: "8080/tcp,8080/udp"
            - name: LIBTORRENT
              value: "v1"

            - name: VPN_ENABLED
              value: "true"
            - name: VPN_CONF
              value: "wg0"
            - name: VPN_PROVIDER
              value: "pia"
            - name: VPN_LAN_NETWORK
              value: "10.0.0.0/8"
            - name: VPN_LAN_LEAK_ENABLED
              value: "false"
            - name: VPN_EXPOSE_PORTS_ON_LAN
              value: "8080/tcp,8080/udp"
            - name: VPN_AUTO_PORT_FORWARD
              value: "true"
            - name: VPN_FIREWALL_TYPE
              value: "auto"
            - name: VPN_HEALTHCHECK_ENABLED
              value: "false"
            - name: VPN_NAMESERVERS
              value: "1.1.1.1@853#cloudflare-dns.com"
            - name: VPN_PIA_DIP_TOKEN
              value: "no"
            - name: VPN_PIA_PORT_FORWARD_PERSIST
              value: "false"
            - name: VPN_PIA_USER
              valueFrom:
                secretKeyRef:
                  name: pia-credentials
                  key: username
            - name: VPN_PIA_PASS
              valueFrom:
                secretKeyRef:
                  name: pia-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: data-volume
              mountPath: /data
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: data-volume
          persistentVolumeClaim:
            claimName: media-pvc
      restartPolicy: Always
