---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pia-credentials
  namespace: arr
spec:
  encryptedData:
    password: AgCHwElFVIhryUEVOqwpYYaPyYFIB1n1jM8QPP3NQe2dZe5+XqFFvW76UeSj8gE2FKcaGpxvcUIGvbZm6MX99og3g1E7Xv8yA6WiMFeWUfdnn6yENRq2fLo3DsPkds+nxECMkoe3JUrE3kHnX24nv/dSzXy6FTCg8TIup6gm7AevoiIoDz+Bn7dQgl17j4CVdKHO3FDLw9aoCW2hQVsamMqdbmUZ43juQPboy/LH68d8+lats64gXbpih/exBIr0zDhIOa9vZHe3g2YkTbTdHImyL95rG2egknu5+WDOsKTR4WH+tPlwliC8G0XEGAw8WsvZ7GjqBUvPkEvfgSCgF3ZMtcZoJg7YN56NQZanE7pek003rm4lHQWLZfiChX2a3EqnHlfU/hmuSxfDrKzQX7+j3MckyMhxolYInvwPYjxEvOi82EpM4vu1JSECLfUV/mdu57bbUJxVXkCuwCMeMEhhcrOtB7o0UkINYH4P6SRpANOb3l3HeFXpU+9M8TlSF0YSIBMxQYyFG7AwLhsBKqxyGmvQzUl1wBHr7/9VUztfhAJN4hZ5Yzmzys3GOnmnQiNgzb5BvodE6FL0sGxL6t7cDd4ltepWXz7H3QrWy3ceBgHiXQkM+kMyzaADArI02fL9Nrr7GmX1aSK6a8pVMPQDZNahmRPu77yybmN/zVqyofL5MESolQvRMMNMstdMdyMO6+aDD9IN00JRCuGXJEERl7Q5f2m7+O5IeRYUdvBv9Q==
    username: AgCzOt/XkJinSzukCJT9uKi1MnxayZRmK3i8CUuJiu1/DU630im1gnzgHvH8NruFLhZbU1oT3WXxctaFb/qw+m316jwO107C1GHLGEYxqqJdl+vfo5nhW48kHTjQ+OUzRuT12vcJza/UL6NhszFsTo9IUSKm4SCNngXMHHLRqlQUSIRsFnQmkaQf6bt1R/BqIuQzJGXONp4kxjm/6hTBXtrdEhnV654hmo/LrQaeW9g6H2+DPjU7WFIZa23vDQhSbozLautnY7vjXulTkc8ZlmiDIvLQ7ELwQLrqoOO42AKf9iOheWT84ClBYx5Max4leYYhNTIvqI+YzRwEualSPOGa3mygTGiuoF3VEmYTNK0eR+hZOGAmmyn29eiOb6a8FbemVWEbQ7OinU/SujNntqMhQY32FNJtOGFjt+2Z+yvMAzRVW0YDhPnmdySLu6TbwoT1HwIWDH3zFVwC2dhnPPHggw6lDRWrTk9JbC3jHK9X7aSfLuzxCP/TlaD0zHXJyaa6K57fT9YgoygRb6wC6xX68RX64nFFTJtPv+g46C+a6pMNyjZgq+ZhkvcuV8NxOFIlOCUt8SqQ1zdGQXm9U/hnCixekyhNj5pLd7DIrElqiteDtlP8JuUEdvMBwA+RgkvqyqgocptAMmo0wFF+Rz6AbFYL9cY1s5FZ7wJRtFCQrYy4M8DddlusqqU5lfgP4xk8gBJHFr9BjQ==
  template:
    metadata:
      name: pia-credentials
      namespace: arr
    type: Opaque
