---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pia-credentials
  namespace: arr
spec:
  encryptedData:
    password: AgBIo/8dw6z0aknwtpkrcZjcIco5gY5ThbZ3/vXUNhYzkkhz2bAZlr8anYf12b6VXscLLYwHvyVwcIBivhW+08mnK5i3ThqiMLZgntMdQJzb1RrwYsMGsRPx7qeYGVpb9mNIgptx6Lcg4NWru+gG242Jf0xcm6FAGSkRBxefoT5YWIk4FcJOjSFupw/bThwaB19iAW/uqyqicTwPNtlaBpaiQgV79ZyIRFKhj4AnUh/itnmmXA6uXl3t4K3iMoDLyAsWJAYmNcTIPiCcUvnmMcUt1R0JB4awbdNZ9vU3rZ6gIFMpZ/pG4YWSOLXTnvQQAfXQvxUM/kCmvs3ovP1S9hwq5SZAkNU3/SxcbmY0u2/+5VemC5pJY+c80DKNUIxnZn0f4KhTmIrLqOZ5xemTnBmwaVIYWFyivcYcCfqbzg+LWAK1iHmp0+d0ilA+xctmXV234HJ6qPYtjde5MRHQIG6+UUP4vnHirc3sQz6QyY+cEGc9VPNIo8uaHqRdRFUyTG8ptKGk+yZ7PKyA3vXo6qVaDqhLMpSUMP3K6qQ0/uIof8llrqDmKTeUrhWNW2Ym6MePT1pkgpNwTvhQCZoJs1sez/6uczVEq1VYx+L0957FVD8HeBqpb15mOCJgLWZZn6iK7Cb9D68e0qM+yPz66WEZjLSExqvg48MZ2N6HEZdvd54cla0nqhHpgvQJ0b7Diq89MEl+olXhri3VRfv/nV6Rga+f4nGwSSiCXJP40FLNVw==
    username: AgAvnVnPWbHu9q3Hocl+OB7FBjIk2ICM+615nTC5g63b9ppaqjlaxWi2yfx/Mbh2RozMc8Sgw8Yt4y1hj5ry4oHf/Z+jb9hB3ztvvV1i/QMzqHijBWvbaP6hTyKJVmoN8TcTNAQBZjPmBXLghGB8brTT8w3XBwyUFVa0Dw7rzuewzvupXbiqg3eD3UB2JXAUaUMTRE8/AIyTJVICoQsx+wYE8uM1bEFvOFX0dhwNy1/S2T2bjoNy8k3GN+5Wi/P/P0tQzrm9E1QGQZ37/gX2RCSoR+d643on3lfO1A2TasrNl2Dl4WrqEK0WhOuvtGJb6d54JpYnnqZba/Kx1qVDHLWpwFEx9AfbW4Z4t3/z81dDd0NJZM4Zik5BX1cAsViGDlbwq28YlXSwCQdM6ZacoYAAJW8cnBSdVa8YhW+g3AApsLazmt4u29V7dl9oCBUzP6fWET5o4iIb3kZyNzZfYKieppck8ePhFY/KCLpe/C4NlHeYcwEKCvTevJ60/oAmnEdGz5YMvviW+RlbvORMCFkQ5yCq7nKx1IWvBMhj1uzOohfgoV0KQ+J1hUf9yPD7G2ZfAieBLvup1g09NdojPf+Ft7tc3M8jDiU0DIsbL2UgNQ3EffE2yNS3MLyHTjlBStPVUP1fqayYznPUh0kegCpkYpmKjgbVEdSLjRggiYbTWG71xlmapXDTjDwF6Pig9jr9PDLOth8TGA==
  template:
    metadata:
      name: pia-credentials
      namespace: arr
    type: Opaque
