---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pia-credentials
  namespace: arr
spec:
  encryptedData:
    password: AgBwA5cgsP1DfQfZDlM3vdsAE4Q+bslwpC4nNUL01T64v1rL5JHo7ibsOh2ZC8Vn9RDt0MmTs/iYu0uBe3ULeGiZ5xKEOJcXKXrL2DWLzxWYk/WE5nqyy7CkmAR92m87MI+xAQduP2cy9EIy4xPlhtDWnylKp+CvfSFjSp6NOEOgMVwzQZSC38cAgfev36ZGIR2wIJkDcOq413JLz1uD1hKesy0g148Q7xpKL4/IP915u7ECBaxlMNnn1mv1Td1A180TVtlHyX4m/TYlCi4q/vfVz6rSC2InT5oNQk90N3vVL/jXSVpb1fHem46xE3/MbYJggNHQ3aQOSkREH17ePXYppBj8m5R5VG1t/z6qwTmeVtaPOsxXx2EhgK0X644RCLTxu/gf1bmXGFFD9qLA3Mdu88uUy9VbA/9geUe1TuM5H5u724mDyCMpIdCe2lKDYznRUOzuKRu46su9QpC+GRI8duoVZXiqxyC0iTvLcVf3vZpIrxA0ldWdpTkuvHyL1S667F0jvrg/u77jrtIPs8nDk+Fj0LMq9ELzPrw4h4JIMr0UY+vZSPWKxQyYZZm7b5RwKQwJpsiqJuDPNmBgttj8recTptSvMZ75WRq5t0WhyK68uGS7ijThfFDXnxysCN/uM1GDiMdxHs9RnyFYCsPM3NUzjQUfPa0/E+cbZlRziYrFYHxd4YzyeiOYbRC5uRpXvHHKTHNV1tMZhFQgfUB7BA7OOfAOzwS04A36La64IQ==
    username: AgAw3R1kcoaeg6dHajcZ5UpKulueuafni0B9Wgbz5EmX75AKwnf59KdGqG8iAJA5vjnn3MK3tj6//McYp8A7ZvJPyghb0mLEwwpHyWZl6SyDsdB4Jl/MIi1mUz1vJOA3xOzRoQZLjm4QF/Y7HalU4uDRrkcCY9p4yf705AfshjsZ15uCOUGqG2UqRkNol6NcJohnc+tarVrBf5+xzeqqfuruyV7FnyrEuXAgjuJtbVHFZtI13N2s8V2cV6nNP6vAxyQlTcaJxBCauq8/X68PyNmPBkfkQvDFu4WRfRZlPoqS0zDRuAPwdJxYW2oD4TTpl9verZ5ImDpyfmhTgdsxef03FF9rZg4F9IsjtxBzrSUCJIsWo7RmQf80icQdmsocFYJuDu3qKRzAvpbnvCtxMaFFBOgMZUS3C5TWcyOpcWkkW7XsPRk46hTgnzYJ4YQC7qlYxl2PGGiffy34/osXJD3nm4+JXBW9XTyETd0lg+nK/u/92e7/loCbEn1t8qZMGMQnwslWmnk1X2g5YLNWZswcMXHM5EDesdoaD/VE5/oVEwbkFYSamGQoqhrSE5X1cUYjoi6PLQKheE8xCCN6D9G9wX/d3QSkgKAvuCwk2UbqvrGlIHDiZGaB4fZXru7+hQtmCio6Wq0g3ra0Fd35QtvpjsHGzGEAGncTcp19XWK5M1gkYCjSLrCTbeGxz0rR+zrjC6J9lwbMsA==
  template:
    metadata:
      name: pia-credentials
      namespace: arr
    type: Opaque
