---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: arr
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 80
      name: webui
      targetPort: webui
