---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pagerduty-secret
  namespace: logging
spec:
  encryptedData:
    service_key: AgAJZq1yDWbGIyhivDoYUZKBfUNOxEYDMhPyV5oOIxhq5MsHSjqyZ0YtFsi3E4gt7XJV4/PPv+QjstpJ6iho+rDawDb89HrlU2mIZcaJmUk5zqyK/nM8c0Z0h1gHATU4n6WzJn2wn3D+PQLvlaiiKD3jk0z+9snpeH3/N74O3uGiyPFn4ekQB4OzURUgCHaoZKs5LAWT0W/KEepFTAAmX9yHbuMDb21ibtLUfyMu7g0nYDllRP7Zrcy5d2CjMpvNh1+xuQYqd/GdxOQ1sH0ygZbZRef9obInY1NCodjZVIRaD9gEJ7mlrZLeQPVqpoqA+dcnGbyHlzS/A529RwoMmXLjkHJki+Rqd/3xcLE7wf2Qf/4bgpS9mPdWkpeMvY8wwReDPWcHkpgGdj4lYF68w5vcieqcjJaSc/o79Y55YEFfQijhzBoUylLeg3vWyDMDCs38x4W+J8ADq3A7QWWqFrZBz8UCUgUjrdkBzHPrnXB6YNY1KGdB3BDREd5A13sk2f+47w/7jhtgr0DwadjyfJxHjqm2QYN7x0NfzNG7La1T9qxqcNHqbA0uD5dZ0kxr10/yU9vf2hj8kmtU8HeeG3EngtS5Ls3dkOPee2pnfhqrIgtImQsY64QjjpGoAP8gPjYDtdUzIQIsVSPi4QRq/3YkbVfgf8MSy0SIXZ368ICNFBA3bTCzdORVQwjOBhvzthC/kvAIq0/0N1KyLlXAEpsfqLgdBRTS/PIpk4NRZmr5uA==
  template:
    metadata:
      name: pagerduty-secret
      namespace: logging
    type: Opaque
