---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logging-stack
  namespace: logging
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-stack
      version: "2.10.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    grafana:
      enabled: true
      persistence:
        enabled: true
        type: pvc
        size: 10Gi
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        annotations:
          nfs.io/storage-path: grafana
    prometheus:
      enabled: true
      server:
        persistentVolume:
          enabled: true
          size: 10Gi
          storageClass: nfs-client
          accessModes:
            - ReadWriteOnce
          annotations:
            nfs.io/storage-path: prometheus
      alertmanager:
        persistence:
          storageClass: nfs-client
    loki:
      singleBinary:
        replicas: 1
        persistence:
          enabled: true
          size: 10Gi
          storageClass: nfs-client
      loki:
        commonConfig:
          replication_factor: 1
        schemaConfig:
          configs:
            - from: "2024-04-01"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        pattern_ingester:
          enabled: true
        limits_config:
          allow_structured_metadata: true
          volume_enabled: true
        ruler:
          enable_api: true
        storage:
          type: "filesystem"

      deploymentMode: SingleBinary

      backend:
        replicas: 0
      read:
        replicas: 0
      write:
        replicas: 0

      ingester:
        replicas: 0
      querier:
        replicas: 0
      queryFrontend:
        replicas: 0
      queryScheduler:
        replicas: 0
      distributor:
        replicas: 0
      compactor:
        replicas: 0
      indexGateway:
        replicas: 0
      bloomCompactor:
        replicas: 0
      bloomGateway:
        replicas: 0
