---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logging-stack
  namespace: logging
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.6.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 10m
  values:
    prometheus:
      prometheusSpec:
        server:
          retention: 30d
          persistentVolume:
            enabled: true
            size: 10Gi
            storageClass: nfs-client
            accessModes:
              - ReadWriteOnce
            annotations:
              nfs.io/storage-path: prometheus
