---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-anyconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-anyconnect
  template:
    metadata:
      labels:
        app: wireguard-anyconnect
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: "1"
          - name: net.ipv4.conf.all.forwarding
            value: "1"
      containers:
        - name: wireguard
          image: masipcat/wireguard-go:latest
          command:
            - sh
            - -c
            - /entrypoint.sh
          ports:
            - containerPort: 8080
              protocol: TCP
              name: healthcheck
          livenessProbe: &probe
            httpGet:
              path: /
              port: healthcheck
          readinessProbe: *probe
          env:
            - name: LOG_LEVEL
              value: info
            - name: ENABLE_HEALTHCHECK
              value: "true"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          resources:
            requests:
              memory: 64Mi
              cpu: "100m"
            limits:
              memory: 256Mi
          volumeMounts:
            - name: cfgmap
              mountPath: /etc/wireguard/wg0.conf
              subPath: wg0.conf
        - name: anyconnect-sidecar
          image: ghcr.io/di0ik/openconnect-vpn:main
          env:
            - name: VPN_SERVER
              valueFrom:
                secretKeyRef:
                  name: anyconnect-config
                  key: vpn_server
            - name: VPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: anyconnect-config
                  key: vpn_username
            - name: VPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: anyconnect-config
                  key: vpn_password
            - name: VPN_GROUP
              valueFrom:
                secretKeyRef:
                  name: anyconnect-config
                  key: vpn_group
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          resources:
            requests:
              memory: 64Mi
              cpu: "100m"
            limits:
              memory: 256Mi
      volumes:
        - name: cfgmap
          secret:
            secretName: wireguard-config-anyconnect
