---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: wireguard
spec:
  encryptedData:
    wg0.conf: AgAdDTb27mKfUtgXKNE4L9tScU5yrDyAEHoy2V5NECsfCST8HP9epZfEUiDjpWmhsXIs6P7TKLXed+avkBCmVm2wNwz9uRjr3zM7vNyOIUyp/K8nSyY5cHpRfViqNS7420a3oUp6cK1tBYKmz9DhNwv4Extt7hrHVsd7APkDlsrB4thlCHl4CsWniIBTg8ovJis/UkN+d/hdoANFBnmsTk9vxaxwDN6FyCA0d/WeUBFl30kCxnEgDdoE278uGpOPr35bDpI2YX56acFstGPah86LU+5c7g5dGyGuoau4LoXfgkery01m0bo567xcLCWc7m7J3sprlGUVPtzg6NVkwuBtRxhDeYNskzrrEoS4sXLRqYaSy75J61/hk3n0Czh3BbUJPlcI0cUUWI3+eiz4ws4g5t/W5+DOL09UP6BKtcku6WDB3WKhuwHGufdKjks1DTkWnlP50GSLWzg/4zXKrxA7s47h5SFnVHXdPJyJDGrX5NE+BO2RjYlH1GliVfv+ND7MRDS9SOM2Lr97v7l0w2Pd1KEXmhwO3PGqse+TgHN5G/gR+6x3y6GNfAzu4nOFTbFYQBiJ0ND0lD480cxcFXBJCKUZ7cvfDw0TzH+egf+WDm5LQSSxN/P5CHThlqJPfVgCx8ot3FjzboED68bzhTCDh11YDLIPJzpPlz8Z0ue8MHWoDD5bDSBmCynoXTvonSjyc29esR02EGpz01VZA9qXzFpIfsKffuF5+t91YtPytKvLLMlyFw3KvhvCUD3xGEHix27Q940HWlZ95LWtpiZ3HN4B2VVw8GnD52D+KGivyM5cHXt9BkDgBPrnJLQh4t67eQWzAEsygFarSXUbzuZC6u1nq5XOGwFT1mwZAtHXo8N3Fw0Xg6ja9wxJuKICE86hEh9/TH1hecAdGO3IiJUJirpkHEGoSRrND1g0tLhsG5NLiDU1jGxitY6CMaVCGWxiB/I2bPXrVlIm7HnrkRBrhdSfzuBeUYY2SOBzOaoploj4kkfMSb9SLqOpenjjpWez4/0XYOpFRjc=
  template:
    metadata:
      name: wireguard-config
      namespace: wireguard
