---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config-anyconnect
  namespace: anyconnect
spec:
  encryptedData:
    wg0.conf: AgA3R7yqlcHRZ22Af15/oe9Ui7KViylyNL83lHzwxYnxeqgySLemEfu0+iyirSsPDPjJTjnoCbp2CDf2RXtGX8tZ5ju1AWH+Yg3SnPwV79tVJ67W09mLb5IMspgFV2JyB5MMA2Vl/XiMWJDW3rhbR2YSFtmt11jF3/85lVj5jhWxtRl2XwMv2FJF3gh1ZRIQdFm0qDanM9T2HgBixYZxzVwMCcxvXZgF1D5KnIzGnbGDYUKuxcTwaMuQWmm6vojMPxBqVxvhODjs+BphufmUfOLPAJ9/ByMLFd4E8RTjbiqWwEQsKAhPQIEGcoCCnnE+kEfTJYGzYfpjNe1YS7sutffEcocoOmjE4Z3faSmWcEza5FG6NycB7dLxbbxD/eCTzaGVF3Dnd3xAQSsS/T3k6wfsxH4Q5MUy26KkInVgii/4fGMKfBZTwph5EISnULv/zbf+LG0noGyoI5eC+2hX5we9fvlf8TQ8ToRujTLVkcuZM9voZTuYBC43yxCgdMq/hQJ0TeV0J/EKuNBlld5pKNp7qES08YitSXQwP3jqcV8FSfwbQ62UQuzO8vizmGS5l6Ycjp74nZYO/SNEh+qo5glmwmSjBsAfp+Z8tHCFyqVtzpfSeWApIXxgWzv2DtjvSQNzSTyKrM8EpCVIRBljR6OKv5WE9EQEtc3Dm6UD39iKIMNFVvcfU0JpDrSbawWZlUFhKS2+YrlByPeEACpyQl2yYoGiN+KOFFz38W4GhuhTUyYMJmX6Szzl1QjZwZLE9NW9zaTxrVTbxqgehxP3YjU+WpFzC662mgVQdaS1GluiLBPlLAjD1JEn9hvK8uk4MXqTv8knkqWiJlUyJAetCve7xBiOOFdyX/IrwPkrDb14JwId/NPF0UNqFQf25di2AdfZMbDcARHf7fU+ACjK9pX4ZevwHTqFmHCZ+mkplejLxdsKLK4XjbZ5JjfoGXgkjGVFdB6RxsL+g7ikG8m9um34JwwIZAIQzVNVMsqogbMYF2B/Rz/3kveutvOvWg/dTCqt2pphTGf34lw=
  template:
    metadata:
      name: wireguard-config-anyconnect
      namespace: anyconnect
