apiVersion: apps/v1
kind: Deployment
metadata:
  name: qui
  namespace: arr
  labels:
    app: qui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qui
  template:
    metadata:
      labels:
        app: qui
    spec:
      containers:
        - name: qui
          image: ghcr.io/hotio/qui:release-1.3.0
          ports:
            - containerPort: 7476
              protocol: TCP
              name: webui
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: qui-config-pvc
      restartPolicy: Always
