---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.dominikstahl.dev`)
      kind: Rule
      services:
        - name: jellyfin
          port: http
