apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: arr
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      version: "2.4.0"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
  interval: 50m
  install:
    remediation:
      retries: 3
    crds: Create
  values:
    image:
      repository: "jellyfin/jellyfin"
      tag: "10.10.7"
    persistence:
      media:
        enabled: true
        readOnly: true
        existingClaim: media-pvc
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
        annotations:
          nfs.io/storage-path: jellyfin
        storageClass: nfs-client
    securityContext:
      capabilities:
        drop:
          - "ALL"
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
